### ISSUE TITLE
TypeError: Cannot convert null to object

### ISSUE THREAD

**Issue by jamescarr** [taterbase/mongoosastic#32]
Got the following while creating a mapping. Will attempt to reproduce in a test:

```
TypeError: Cannot convert null to object
    at getCleanTree (/home/jamescarr/Projects/lead-management-system/node_modules/mongoosastic/lib/mapping-generator.js:78:10)
    at getCleanTree (/home/jamescarr/Projects/lead-management-system/node_modules/mongoosastic/lib/mapping-generator.js:93:28)
    at Generator.generateMapping (/home/jamescarr/Projects/lead-management-system/node_modules/mongoosastic/lib/mapping-generator.js:5:19)
    at createMappingIfNotPresent (/home/jamescarr/Projects/lead-management-system/node_modules/mongoosastic/lib/mongoosastic.js:132:13)
    at Function.createMapping (/home/jamescarr/Projects/lead-management-system/node_modules/mongoosastic/lib/mongoosastic.js:38:5)
    at /home/jamescarr/Projects/lead-management-system/loader.coffee:9:23

```

**Comment by niftylettuce** [comment]
most likely due to embedded document schema as far as i can tell

**Comment by taterbase** [comment]
This issue is 8 months old and has no information on how to recreate. I'm going to close it for now until we can get more info.
