### ISSUE TITLE
Expose 'filter' to mongoosastic Models

### ISSUE THREAD

**Issue by martindale** [taterbase/mongoosastic#39]
I'm aware that the DSL for elasticsearch is exposed in mongoosastic, but I can't seem to access `filter` on a mongoosastic-enabled model.

As per [the DSL documentation for geo-distance filter](http://www.elasticsearch.org/guide/reference/query-dsl/geo-distance-filter.html) I'm trying to search for documents using the following:

```
Location.search({
  query: {
    match_all: {}
  }
, filter: {
    geo_distance : {
        distance: '200km'
      , 'location.geo': {
            lat: lat
          , lon: lon
        }
    }
  }
}, function(err, results) {
// err: {}
// results: undefined
});
```

...which errors out.  My model is something like this:

```
LocationSchema = {
  , geo: {
        geo_point: {
          type: String,
          es_type: 'geo_point',
          es_lat_lon: true
        }
      , lon: { type: Number }
      , lat: { type: Number }
    }
}
```

As far as I can tell, when including both `query` and `filter`, there's either something broken in the binding to `elastical`, or I've just not set my query up correctly.  Please advise!

**Comment by martindale** [comment]
It looks like elasticsearch is also throwing an exception in this case, likely due to the `geo_point` index not getting created?

```
[2012-10-01 16:42:40,406][DEBUG][action.search.type       ] [Stentor] [locations][4], node[k_KGJRdUTYeseihAA_QikA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@4cb2fd30]
org.elasticsearch.search.SearchParseException: [locations][4]: query[ConstantScore(NotDeleted(*:*))],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"match_all":{}},"filter":{"geo_distance":{"distance":"200km","location.geo":{"lat":"35.7765","lon":"-78.6444"}}}}]]
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:554)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:469)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:228)
    at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteQuery(SearchServiceTransportAction.java:140)
    at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.sendExecuteFirstPhase(TransportSearchQueryThenFetchAction.java:80)
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:205)
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:192)
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$2.run(TransportSearchTypeAction.java:178)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
Caused by: org.elasticsearch.index.query.QueryParsingException: [locations] failed to find geo_point field [location.geo]
    at org.elasticsearch.index.query.GeoDistanceFilterParser.parse(GeoDistanceFilterParser.java:177)
    at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:223)
    at org.elasticsearch.index.query.IndexQueryParserService.parseInnerFilter(IndexQueryParserService.java:254)
    at org.elasticsearch.search.query.FilterParseElement.parse(FilterParseElement.java:33)
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:542)
    ... 10 more
```

I tried switching my model to the following after this, to no avail:

```
LocationSchema = {
    geo: {
        type: Schema.Types.Mixed
      , es_type: 'geo_point'
      , es_lat_lon: true
      , lon: { type: Number }
      , lat: { type: Number }
    }
}
```

**Comment by taterbase** [comment]
This is a super old issue and I don't really have time to investigate/replicate. Please let me know if this is still an issue.
