### ISSUE TITLE
mapping generator error 

### ISSUE THREAD

**Issue by pgherveou** [taterbase/mongoosastic#65]
Hello there. Thanks for this fantastic project, I noticed a small bug as I updated my schema
mongoosastic fail to generate my schema mapping when my schema has complex attributes like the following:

``` javascript
new Schema({
    recents: {
      list: [{type: ObjectId, ref: 'User'}],
      size: {type: Number}
    }
  });
```

I don't even need to index this attributes but 
createMapping generate the following error 

```
        else if ( paths[field].caster && paths[field].caster.instance ) {
                              ^
TypeError: Cannot read property 'caster' of undefined
  at getCleanTree (/Users/pg/Jogabo/app/node_modules/mongoosastic/lib/mapping-generator.js:122:31)
  at getCleanTree (/Users/pg/Jogabo/app/node_modules/mongoosastic/lib/mapping-generator.js:148:28)
  at Generator.generateMapping (/Users/pg/Jogabo/app/node_modules/mongoosastic/lib/mapping-generator.js:5:19)
  at createMappingIfNotPresent (/Users/pg/Jogabo/app/node_modules/mongoosastic/lib/mongoosastic.js:142:13)
  at Function.module.exports.schema.statics.createMapping (/Users/pg/Jogabo/app/node_modules/mongoosastic/lib/mongoosastic.js:39:5)
```

**Comment by taterbase** [comment]
Thanks for the issue, I'll look into this as soon as possible.

**Comment by pgherveou** [comment]
I don't know if this is related or not but I just realised that nested field are also ignored by the mapping

**Comment by itamarwe** [comment]
I have the same problems: createMapping fails, and the nested field is ignored...

**Comment by jeffwhelpley** [comment]
+1. Any updates here?

**Comment by taterbase** [comment]
Hey Jeff,

Sorry unfortunately I have been very busy. I am currently the most active contributor but that doesn't say much since I haven't had a ton of time. Pull Requests are very welcome however!

Thanks,
- George

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/3
